//
//  gameModelData.swift
//  TheGameShop
//
//  Created by Wojciech Jankowiak on 11/10/2018.
//  Copyright © 2018 Wojciech Jankowiak. All rights reserved.
//

import Foundation

class gameModelData {
    var  gamesData : [Game ] =
        [Game (name_: "Diablo III", description_: "Diablo III to kolejna część niezwykle popularnej serii hack'n'slash, która zadebiutowała w 1996 roku. Produkcja zawiera kilka rozwiązań znanych z poprzednich części marki i wprowadza mnóstwo nowych pomysłów. Jej producentem jest firma Blizzard Entertainment, znana z wielu udanych i świetnie sprzedających się marek (m.in. World of Warcraft, StarCraft). W trzeciej odsłonie Diablo wracamy do świata Sanktuarium, aby jeszcze raz zmierzyć się z siłami ciemności i tytułowym demonem. Gra rozpoczyna się w dwadzieścia lat po wydarzeniach znanych z Diablo II, w którym grupa herosów zatriumfowała nad złem. Na katedrę w Tristram spada tajemnicza kometa, która rozbudza spoczywające w niej piekielne zastępy. Świat Sanktuarium potrzebuje więc nowych bohaterów: do akcji wkraczają barbarzyńca, czarownik, mnich, szaman i łowca demonów. Każdy z nich dysponuje własnym tłem fabularnym.", imageName_: "Diablo_III", price_: 122.5, platform_ : "PC", type_ : "Strategy", isInBasket_: false, latitude_: 51.106612, longitude_:17.010692, isFavourite_: true),
         Game (name_: "Grand Theft Auto 5", description_: "Grand Theft Auto V – kolejna odsłona kultowej serii gangsterskich gier akcji studia Rockstar North – zabiera nas do świata wzorowanego na Kalifornii. W uniwersum Grand Theft Auto stan nosi nazwę San Andreas i składa się między innymi z miasta Los Santos, które stanowi główne miejsce akcji piątki. Tworząc swój świat Rockstar jeszcze raz postanowił sparodiować znaną nam rzeczywistość, ośmieszając ideologie, produkty, zjawiska i zachowania ludzi. Jednocześnie twórcy GTA V postarali się o rozbudowanie swojej produkcji pod każdym względem w stosunku do poprzednich odsłon cyklu.", imageName_: "GTA_V", price_: 99.99, platform_: "XBOX", type_ : "Racing", isInBasket_: false, latitude_: 51.101053, longitude_:16.996420, isFavourite_: true),
         Game (name_: "Witcher 3", description_: "Wiedźmin 3: Dziki Gon (The Witcher 3: Wild Hunt) na komputery osobiste to trzecia odsłona popularnej serii gier RPG akcji opartej na prozie Andrzeja Sapkowskiego. Tytuł wyprodukowało studio CD Projekt RED, czyli zespół odpowiedzialny również za dwie poprzednie części – Wiedźmina z 2007 roku i Wiedźmina 2: Zabójcy Królów z 2011 roku. Produkcja w wersji na PC-ty nie odbiega zawartością od konsolowych wydań, ale użytkownicy „blaszaków” otrzymali kilka niedostępnych na pozostałych platformach sprzętowych elementów.", imageName_: "Witcher_3", price_: 220.00, platform_ : "PS4", type_ : "RPG", isInBasket_: false, latitude_: 51.101257, longitude_:17.031971, isFavourite_: false),
         Game (name_: "Medal of honor", description_: "Medal of Honor to pierwszoosobowa strzelanina, stanowiąca swoisty restart serii, która została zapoczątkowana w 1999 roku na konsoli PlayStation. Po raz pierwszy w historii cyklu gracze otrzymali szansę wzięcia udziału we współczesnym konflikcie. Produkcja została opracowana przez dwa studia deweloperskie: EA Los Angeles zaprojektowało opcję dla pojedynczego gracza, natomiast EA DICE opracowało dynamiczny tryb wieloosobowy.", imageName_: "MOH", price_: 110.00, platform_ : "PC", type_ : "Action", isInBasket_: false, latitude_: 51.113214, longitude_:17.039708, isFavourite_: false),
         Game (name_: "Crash Bandicoot", description_: "Nowe wersje przygód Crasha zostały kompletnie przebudowane. Deweloperzy nie ograniczyli się tylko do delikatnie usprawnionej grafiki, ale właściwie wszystko stworzyli od nowa. Oznacza to całkowicie przerobione poziomy, z nowymi teksturami i efektami specjalnymi. Także modele postaci zostały przystosowane do obecnych standardów. Ponadto zmieniono przerywniki filmowe, inspirując się tymi z oryginalnych wydań.", imageName_: "Crash", price_: 159.99, platform_ : "PS4", type_ : "Action", isInBasket_: false, latitude_: 51.113414, longitude_:17.058999, isFavourite_: false),
         Game (name_: "Bloodborne", description_: "Klasyczne RPG akcji japońskiego studia From Software. Tytuł jest autorską produkcją Hidetakiego Miyazakiego, twórcy legendarnego Demon's Souls oraz serii Dark Souls. Według twórców, Bloodborne należy traktować jako duchowego następcę serii Dark Souls oraz poprzednich i mniej znanych gier studia From Software, takich jak King's Field, które ukazały się na konsolach PlayStation i PlayStation 2. Tytuł powstaje w ścisłej współpracy z firmą Sony Computer Entertainment.", imageName_: "Bloodborne", price_: 130.00, platform_ : "PS4", type_ : "Strategy", isInBasket_: false, latitude_: 51.113414, longitude_:17.058999, isFavourite_: false),
         Game (name_: "Dawn of War", description_: "Warhammer 40 000: Dawn of War – Dark Crusade to drugie (po Winter Assault) rozszerzenie do znanej strategii firmy Relic Entertainment, odpowiedzialnej m.in. za kultowego Homeworlda. Podstawową nowinką, jaką wprowadza „Mroczna Krucjata”, są dwie nowe rasy – Necroni i Tau.", imageName_: "Warhammer", price_: 75.00, platform_ : "PC", type_ : "Strategy", isInBasket_: false, latitude_: 51.095173, longitude_:17.019532, isFavourite_: false),
         Game (name_: "Prince of Persia", description_: "Najnowsza odsłona „Księcia Persji” stworzona została przez studio Ubisoft Montreal – to samo, które odpowiada za trzy poprzednie edycje PoP - Sands of Time, Warrior Within i The Two Thrones. Stanowi ona jednak początek zupełnie nowego rozdziału przygód tytułowego bohatera. Zupełnie nowy świat, nowa fabuła i nowy książę. Grę napędza silnik o nazwie Anvil (ten sam, który został użyty w Assassins Creed).", imageName_: "PoP", price_: 10.00, platform_ : "XBOX", type_ : "Action", isInBasket_: false, latitude_: 51.120304, longitude_:17.054101, isFavourite_: false),
         Game (name_: "Gothic II Gold", description_: "Sequel jednej z najlepszych gier akcji/cRPG roku 2001. Podobnie jak w części poprzedniej akcja Gothic II toczy się w świecie fantasy i kontynuuje fabułę poprzedniczki, tj. wojny pomiędzy siłami zła (cała masa potworów, Orków i Ogrów pod przewodnictwem Smoków) i Ludźmi. Jednak tym razem nie poruszamy się już tylko wewnątrz kolonii przestępców objętej zasięgiem magicznej bariery, a na jej zewnątrz. Akcja toczy się w nowych bardzo rozległych i różnorodnych lokacjach, m.in. miasteczko nadmorskie, klasztor, biblioteka, farma, Wyspa Smoków, zamek oblężony przez Orki. Oczywiście spotkamy tu też klika znajomych terenów. Praktycznie rzecz biorąc zasady gry nie uległy diametralnym zmianom. Mamy oczywiście kilka usprawnień, tj. nowe klasy postaci (m.in. magician, henchmen i dragon hunters), nowe gildie oraz nowe czynności które może wykonywać nasz bohater (m.in. tworzenie różnych mikstur).", imageName_: "G2", price_: 50.00, platform_ : "PC", type_ : "RPG", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Assassins Creed II", description_: "Podobnie jak miało to miejsce w pierwszej części serii, fabuła wydanego na platformę X360, PS3 itd. Assassin's Creed II opiera się na dwóch wątkach: współczesnym i historycznym. W tym pierwszym przychodzi nam śledzić dalsze losy znanego z „jedynki” Desmonda Milesa. Protagoniście udało się uciec z siedziby Abstergo Industries w towarzystwie Lucy Stillman i jej przyjaciół – Shauna oraz Rebecci. Bohaterowie trafiają do kryjówki zaopatrzonej w udoskonaloną wersję Animusa. Nie mając innego wyjścia, Desmond po raz kolejny zanurza się we wspomnieniach swoich przodków…", imageName_: "AC2", price_: 110.00, platform_ : "XBOX", type_ : "RPG", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Watch_Dogs", description_: "Watch Dogs to gra akcji z otwartym, nafaszerowanym technologicznymi nowinkami Chicago, w której najpotężniejszą bronią bohatera stają się umiejętności hakerskie. Jest to dzieło kilku studiów, którymi przewodniczy Ubisoft Montreal, znane z takich serii jak Assassin’s Creed, Tom Clancy’s Rainbow Six czy Far Cry. Na potrzeby tej produkcji stworzono nowy silnik Disrupt, pozwalający na stworzenie tętniącego życiem, szczegółowego miasta. Wcielamy się w postać byłego przestępcy imieniem Aiden Pearce, czyli antybohatera, który jest ekspertem we włamywaniu się do systemów elektronicznych. Dzięki temu potrafi, bagatela, wywołać karambol poprzez manipulację światłami na skrzyżowaniu, podłączyć się do miejskiego systemu monitoringu czy włamać do telefonu mijanej osoby, aby dowiedzieć się czegoś więcej na jej temat i na przykład zaingerować w przebieg jej codziennego życia (uratować przed złodziejaszkiem, wykraść pieniądze z konta itp.). Talenty Pearce'a pozwalają mu na kontrolowanie prawie każdego elementu otaczającego go nowoczesnego świata.", imageName_: "w_d", price_: 220.00, platform_ : "PS4", type_ : "RPG", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Fallout 4", description_: "Fallout 4 na komputery PC jest czwartą pełnoprawną odsłoną kultowego cyklu post-apokaliptycznych gier RPG, zapoczątkowanego w 1997 roku przez studio Black Isle oraz koncern Interplay. Po zamknięciu studia oryginalnego dewelopera i chłodnym przyjęciu wydanego na PlayStation 2 Fallout: Brotherhood of Steel, prawa do marki przejęła firma Bethesda i to właśnie jej wewnętrzne studio odpowiada zarówno za trzecią, jak i czwartą część serii. Studio znane było wcześniej głównie z serii The Elder Scrolls, której najpopularniejsza odsłona, Skyrim, ukazała się w 2011 roku na PC-tach oraz konsolach PlayStation 3 i Xbox 360. Tytuł w wersji na komputery osobiste oferuje kilka usprawnień względem konsolowych wydań. Gra oferuje opcję gry między innymi w 60 klatkach na sekundę i rozdzielczości przekraczającej Full HD. Na PlayStation 4 i Xboksie One Fallout 4 działa natomiast „tylko” w 30 klatkach i 1080p. Kolejną ważną rzeczą są modyfikacje, które w wersji PC-towej rozprowadzane są niemal na tych samych zasadach, co w przypadku Skyrima. Krótko pisząc, gracze mają praktycznie pełną dowolność w tworzeniu modyfikacji.", imageName_: "f4", price_: 169.00, platform_ : "XBOX", type_ : "RPG", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "The Last Of Us", description_: "The Last of Us to interaktywny survival horror stanowiący połączenie dynamicznej gry akcji z delikatnymi elementami przygodowymi. Tytuł ten wyszedł spod ręki studia Naughty Dog, czyli ojców takich serii jak Uncharted, Jak & Daxter i Crash Bandicoot. Akcja toczy się w niedalekiej przyszłości, 20 lat po tym jak tajemnicza zaraza zdziesiątkowała naszą cywilizację. Opuszczone miasta objęły we władanie rośliny i zmutowane ofiary, a ocalali ludzie walczą ze sobą o jedzenie i broń. Fabuła obraca się wokół dwójki bohaterów – mającego ponad 40 lat przemytnika broni i narkotyków imieniem Joel oraz nastoletniej sieroty Ellie - i koncentruje się na ich próbach przeżycia w tej przerażającej rzeczywistości. Podczas większości etapów wcielamy się w postać Joela, natomiast jego towarzyszka kierowana jest przez sztuczną inteligencję. Ellie wspomaga nas w walce, jak również informuje o nadciągającym niebezpieczeństwie, czy nawet sugeruje niekiedy ścieżkę, którą powinniśmy podążyć.", imageName_: "tlou", price_: 220.00, platform_ : "PS4", type_ : "Strategy", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Rayman Legends", description_: "Rayman Legends to kolejna radosna i kolorowa platformówka o przygodach tytułowego bohatera. Produkcja została stworzona przez Michela Ancela, czyli znanego francuskiego dewelopera, który wykreował markę Rayman oraz serię Beyond Good & Evil. W Rayman Legends wracamy do postaci Raymana, który musi przemierzyć kolejne poziomy, aby uratować świat. Tym razem twórcy przygotowali mieszankę różnych legendarnych krain – od starożytnej Grecji, aż po średniowieczne zamki. Bohater jak zwykle otrzymuje pomoc ze strony swoich wiernych kompanów – w tym sympatycznego stworka imieniem Globox. Rayman Legends w znacznym stopniu przypomina poprzednią odsłonę serii, czyli Rayman Origins. To w dalszym ciągu pozornie prosta, a jednak dość wymagająca zręcznościowa platformówka z trybem kooperacji dla czterech osób. Gra została wzbogacona o możliwość dołączania i wychodzenia z rozgrywki w dowolnym momencie oraz parę innych dodatków.", imageName_: "rayman_legends", price_: 220.00, platform_ : "PC", type_ : "Racing", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "God of war remastered", description_: "God of War III jest kolejną częścią znakomitego cyklu gier akcji. Tym razem jest to remaster przygotowany z okazji dziesiątej rocznicy istnienia serii, przeznaczony na konsolę PlayStation 4. W God of War III otrzymujemy nowe rodzaje broni, przy czym każda z nich wymaga odmiennego stylu walki. Przykładowo rękawice Cestus, połączone łańcuchami z wielkimi, kolczastymi kulami, stanowią świetną broń dystansową, mogą także odrzucać zbyt blisko podchodzących do Kratosa wrogów.", imageName_: "gowr", price_: 220.00, platform_ : "PS4", type_ : "Action", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Uncharted 4", description_: "Uncharted 4: Kres Złodzieja (Uncharted 4: A Thief's End) na konsolę PS4 jest czwartą odsłoną serii Uncharted. Jednocześnie jest to pierwsza część (nie licząc składanki Uncharted: Kolekcja Nathana Drake'a) przeznaczona na konsolę PS4. Za stworzenie gry odpowiada ponownie studio Naughty Dog, znane z takich hitów jak The Last of Us, Crash Bandicoot czy też Jak and Daxter: The Precursor’s Legacy.", imageName_: "u4", price_: 220.00, platform_ : "PS4", type_ : "Action", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
         Game (name_: "Spyro reignited Trilogy", description_: "Spyro Reignited Trilogy jest kolekcją unowocześnionych wersji trzech platformówek 3D (Spyro the Dragon, Spyro 2: Ripto’s Rage! oraz Spyro: Year of the Dragon), które pierwotnie zostały wydane w latach 1998-2000 na pierwszej konsoli PlayStation. Bohaterem gier jest uroczy, fioletowy smoczek Spyro. Za stworzenie oryginalnych tytułów odpowiadało dobrze znane studio Insomniac Games (twórcy m.in. Ratcheta & Clanka oraz Sunset Overdrive). Przygotowaniem mocno odświeżonych pod względem grafiki remake’ów zajęła się firma Toys For Bob.", imageName_: "spyro", price_: 220.00, platform_ : "PS4", type_ : "Action", isInBasket_: false, latitude_: 51, longitude_:17, isFavourite_: false),
    ]
}
